sudo: required
services:
  - docker
before_install:
  - docker build -t christoskokolios/docker-react -f Dockerfile.dev .
scripts: 
   - docker run christoskokolios/docker-react npm run test -- --coverage CI=true
language: generic 
