sudo: required
services:
  - docker
before_install:
  - docker build -t christoskokolios/docker-react -f Dockerfile.dev .
scripts: 
   - docker run -e CI=true christoskokolios/docker-react npm run test
language: generic 
